require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-rake

AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.1.2
  Exclude:
    - bin/**/*
    - config/**/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 34

Metrics/MethodLength:
  Max: 13

Lint/MissingSuper:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
